### ISSUE TITLE
minor doc updates

### ISSUE THREAD

**Issue by evdevr** [aws-samples/rancher-on-aws-workshop#62]
- in `50-additional-integrations`, script download section is not clearly labeled workshop vs not in workshop w/ expandable sections
- in `30-creating-a-cluster/32-creating-rke2-cluster`, Machine Pools area there's a copy/paste issue on the VPC/Subnet that creates two duplicate bullets

**Comment by zackbradys** [comment]
want me to submit a merge for this @marshkkm?

**Comment by zackbradys** [comment]
updated and fixed in PR #67
