### ISSUE TITLE
Rancher App List not working on RKE2 clusters

### ISSUE THREAD

**Issue by evdevr** [aws-samples/rancher-on-aws-workshop#64]
the installed apps section of the local cluster is only showing me the flask demo app. longhorn, neuvector, and monitoring are not showing up in that menu despite being installed via the rancher app chart store.

the imported eks-cluster is showing the cattle-system and fleet-agent apps after import just fine. the eks-cluster also shows longhorn and the longhorn-crds when i install it (with prereqs of course) in the eks-cluster. seems like just the rke2 cluster is not showing installed apps properly.

**Comment by zackbradys** [comment]
it should be showing. did you try force reloading or logging out and back into it?

**Comment by evdevr** [comment]
rookie mistake- did not change the namespace filter. 🤦

user error, closing with no changes.

**Comment by zackbradys** [comment]
It does bring up a good point... should we call out the namespace filter step a bit more? it happens quite often to users.
